apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  - port: 443
    targetPort: 443
    name: web443
  type: NodePort
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: jboss/keycloak
        env:
        - name: DB_VENDOR
          value: MYSQL
        - name: DB_ADDR
          value: keycloak-db
        - name: DB_DATABASE
          value: keycloak_users
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: P@ssw0rd
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: P@ssw0rd
        - name: KEYCLOAK_HTTPS_PORT
          value: 443
        - name: PROXY_ADDRESS_FORWARDING
          value: "true" 
        ports:
        - containerPort: 8080
          name: port80
        - containerPort: 443
          name: port443
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-db
        tier: web
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-db-disk
      containers:
        - name: keycloak-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: P@ssw0rd
            - name: MYSQL_PASSWORD
              value: P@ssw0rd
            - name: MYSQL_USER
              value: keycloak_users
            - name: MYSQL_DATABASE
              value: keycloak_users
          image: mysql:8.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  type: NodePort
  selector:
    app: keycloak-db
    tier: web
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-db-disk
spec:
  # storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi